tips = new Array(68);
code = new Array(68);
tips[0] = '安装软件包';
code[0] = 'sudo zypper in <软件包名>';
tips[1] = '升级软件包';
code[1] = 'sudo zypper up <软件包名>';
tips[2] = '卸载软件包及其依赖';
code[2] = 'sudo zypper rm -u <软件包名>';
tips[3] = '不安装推荐的软件包';
code[3] = 'sudo zypper in --no-recommends <软件包名>';
tips[4] = '系统升级';
code[4] = 'sudo zypper dup (请只启用新版的 oss/non-oss/oss-update/non-oss-update 源)';
tips[5] = '在已启用的软件源中搜索软件包';
code[5] = 'sudo zypper se <软件包名>';
tips[6] = '只从固定软件源安装软件包';
code[6] = 'sudo zypper in <软件包名> -r <软件源别名>';
tips[7] = '添加软件源';
code[7] = 'sudo zypper ar -f <软件源 URL> <软件源别名>';
tips[8] = '添加 DVD/Live CD ISO 为软件源';
code[8] = 'sudo zypper ar "iso:/?iso=路径" <软件源别名>';
tips[9] = '安装软件集 (pattern)';
code[9] = 'sudo zypper in -t pattern <软件集名>';
tips[10] = '移除软件源'
code[10] = 'sudo zypper rr <软件源别名>';
tips[11] = '列出已添加的软件源 (不管启用没启用)';
code[11] = 'zypper lr';
tips[12] = 'openSUSE 下没有 gtksu 的哦！';
code[12] = '只有 gnomesu，在 libgnomesu 软件包里';
tips[13] = '刷新全部已启用的软件源';
code[13] = 'sudo zypper ref';
tips[14] = '启用软件源';
code[14] = 'sudo zypper mr -e <软件源别名>';
tips[15] = '禁用软件源';
code[15] = 'sudo zypper mr -d <软件源别名>';
tips[16] = '启用全部软件源';
code[16] = 'sudo zypper mr -ea';
tips[17] = '禁用全部软件源';
code[17] = 'sudo zypper mr -da';
tips[18] = '修改软件源优先级';
code[18] = 'sudo zypper mr -p <优先级 0~200 越小越优先> <软件源别名>';
tips[19] = '列出可用更新 (需要启用 oss-update/non-oss-update 源)';
code[19] = 'sudo zypper lu';
tips[20] = '列出你系统需要的更新补丁 (需要启用 oss-update/non-oss-update 源)';
code[20] = 'sudo zypper lp';
tips[21] = '查看提供指定功能的软件包';
code[21] = 'sudo zypper wp';
tips[22] = '列出全部可用补丁 (需要启用 oss-update/non-oss-update 源)';
code[22] = 'sudo zypper patches'
tips[23] = '列出软件包内容';
code[23] = 'rpm -ql <软件包名称>';
tips[24] = '查找某个文件属于哪个软件包';
code[24] = 'rpm -qf <文件完整路径>';
tips[25] = '不刷新软件源直接安装软件包';
code[25] = 'sudo zypper in --no-refresh <软件包名>';
tips[26] = '安装更新补丁';
code[26] = 'sudo zypper patch <补丁名 openSUSE-2013-xxx>';
tips[27] = '安装软件包源代码及其依赖';
code[27] = 'sudo zypper si <软件包名>';
tips[28] = '安装软件包的编译依赖';
code[28] = 'sudo zypper si -d <软件包名>';
tips[29] = '查看 zypper 帮助';
code[29] = 'zypper --help';
tips[30] = '查看 zypper 某个命令的帮助';
code[30] = 'zypper <命令或命令缩写> --help';
tips[31] = '单独安装某个软件包的推荐软件包';
code[31] = 'sudo zypper inr <软件包名>';
tips[32] = '降级软件包';
code[32] = 'sudo zypper in --oldpackage <软件包名>-<版本>-<架构>';
tips[33] = '自动同意软件包授权使用许可';
code[33] = 'sudo zypper in -l <软件包名>';
tips[34] = '只下载软件包，不安装';
code[34] = 'sudo zypper in -d <软件包名>';
tips[35] = '搜索推荐了指定软件包的软件包';
code[35] = 'sudo zypper se --recommends <指定软件包名>';
tips[36] = '搜索提供了指定功能的软件包';
code[36] = 'sudo zypper se --provides <功能>';
tips[37] = '显示指定补丁的完整信息';
code[37] = 'sudo zypper patch-info <补丁>';
tips[38] = '查询指定软件包的依赖';
code[38] = 'sudo zypper info --requires <软件包名>';
tips[39] = '查询指定软件包推荐的软件包';
code[39] = 'sudo zypper info --recommends <软件包名>';
tips[40] = '查询依赖指定软件包的软件包';
code[40] = 'sudo zypper se --requires <软件包名>';
tips[41] = '清除已升级软件包之前的旧配置(谨慎使用，升级会恢复 /etc 中默认配置)';
code[41] = 'sudo find /etc -name "*.rpmsave" -print -delete';
tips[42] = '编译时缺少 xxx.h 的查找方法';
code[42] = 'find /usr/include -name "xxx.h"';
tips[43] = '创建一个文件夹及其子文件夹';
code[43] = 'sudo mkdir -p <文件夹>/{<子文件夹1>,<子文件夹2>}';
tips[44] = '列出指定文件夹内容';
code[44] = 'ls <指定文件夹路径>';
tips[45] = '前往指定文件夹';
code[45] = 'cd <指定文件夹路径>';
tips[46] = '前往指定文件夹后还能回来';
code[46] = 'pushd <指定文件夹路径>, ls, popd';
tips[47] = '在终端查看日期和显示日历'
code[47] = 'date,cal'
tips[48] = '查看某个磁盘分区可用空间'
code[48] = 'df /dev/sdaX'
tips[49] = '以直观的方式显示系统可用内存'
code[49] = 'free -h'
tips[50] = '将工作目录改为先前的工作目录'
code[50] = 'cd -'
tips[51] = '确定文件类型'
code[51] = 'file <你要确定类型的文件>'
tips[52] = '常用字符类'
code[52] = '匹配任意一个字母或者数字，[:alnum:]； 匹配任意一个字母，[:alpha:]；匹配任意一个数字，[:digit]'
tips[53] = '复制整个目录到另一个目录下'
code[53] = 'cp -r <想要复制的目录> <目标目录>'
tips[54]='合并多个 flv 视频文件'
code[54]='mencoder -oac pcm -ovc copy -idx -o <合并后的文件> <需要合并的文件1> <需要合并的文件2> ... ... '
tips[55]='将文件移动到一个目录中，只移动目标目录中不存在的文件'
code[55]='mv -u file1 file2'
tips[56]='创建符号链接'
code[56]='ln -s item link'
tips[57]='花括号扩展，一次性创建目录 FileA FileB FileC'
code[57]='mkdir File{A,B,C}'
tips[58]='花括号扩展，一次性创建以日期为文件名的文件夹'
code[58]='mkdir {2013..2053}-0{1..9} {2013..2053}-{10..12}'
tips[59]='命令替换'
code[59]='ls -l $(which cp)'
tips[60]='在终端中移动光标到行首,移动到行末'
code[60]='Ctrl-A，Ctrl-B'
tips[61]='改变文件所有者和群组'
code[61]='chowm [ower][:[group]] file'
tips[62]='以树状模式输出进程列表'
code[62]='pstree'
tips[63]='将文件打包成 iso 映像'
code[63]='mkiso -o <目标 ISO 文件的名称> <要打包的目录>'
tips[64]='修复闪存'
code[64]='先卸载闪存，sudo fsck /dev/sdbX'
tips[65]='从 CD 中创建 iso 镜像'
code[65]='dd if=/dev/cdrom of=XXX.ISO'
tips[66]='从 /etc/passwd 文件中提取每一行的第一个字段'
code[66]='cut -d ':' -f 1 /etc/passwd | head'
tips[67]='合并文本行'
code[67]='paste file1.txt file2.txt'
tips[68]='连接两个文件中具有相同字段的行'
code[68]='join file1 file2'







index = Math.floor(Math.random() * tips.length);
document.write("&nbsp;"+tips[index]+':&nbsp;&nbsp;<code>'+code[index]+'</code>');

